services:
  auth-service:
    image: excard-auth-service
    container_name: auth-service
    build:
      context: ./authentication_autorization
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/excard_db
      JWT_SECRET: 6A/rmc3XXBcR0KBadmew81PuaeFA0hUple8BtfCQL3w=
    networks:
      - excard_net
    restart: unless-stopped

  card-loader:
    image: excard_load_service
    container_name: load_service
    build:
      context: ./card_loader
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/excard_db
    networks:
      - excard_net
    restart: unless-stopped

  management-service:
    image: excard-management-service
    container_name: management-service
    build:
      context: ./gestione_utente
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/excard_gestione_utente
      JWT_SECRET: 6A/rmc3XXBcR0KBadmew81PuaeFA0hUple8BtfCQL3w=

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - excard_net
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  excard_net: