spring.application.name=gestione_utente
spring.data.mongodb.uri=mongodb://localhost:27017/management_db
server.port=8081
server.servlet.session.cookie.domain=localhost
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true
#jwt.secret=${JWT_SECRET}